language: python
python:
  - "3.10"
  - "3.11"
  - "3.12"
env:
  - DJANGO_VERSION=4.2
  - DJANGO_VERSION=4.0
addons:
    sonarcloud:
      organization: $SC_ORG
      token: $SC_TOKEN

matrix:
    exclude:
    - python: "3.10"
      env: DJANGO_VERSION=4.2
      
before_install:
  - pip install -U pip
  - pip install -q Django==$DJANGO_VERSION
  - pip install -U wheel setuptools flake8
install:
  - python setup.py -q install
script:
  - flake8 ./src
  - python setup.py test --addopts "--cov=django_keycloak --cov-report xml:coverage.xml"
  - sonar-scanner

cache:
    directories:
    - '$HOME/.sonar/cache'

after_success:
  - pip install codecov
  - codecov
